server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meeting?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: willian
    password: L.Willian1024
  session:
#    store-type: redis
    store-type: jdbc
    jdbc:
      initialize-schema: always
# redis
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）

# 超时y一定要大于0

mybatis:
  mapper-locations:
    - classpath:mapping/*Mapper.xml #注意：一定要对应mapper映射xml文件的所在路径
    - classpath:mappingDao/*Dao.xml
  type-aliases-package: com.harman.meeting_management.entity # 注意：对应实体类的路径

#showSql
logging:
  level:
    com:
      harman:
        meeting_management:
          mapper: debug


# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头